p8105_hw2_kw3180
================
Kino Watanabe
2025-09-26

``` r
library(tidyverse)
library(readxl)
```

# Question 1

### Clean the data in pols-month.csv:

``` r
pols_month_df = 
    read_csv("fivethirtyeight_datasets/pols-month.csv") |> 
    janitor::clean_names() |> 
    separate(mon, into = c("year", "month", "day"), convert = TRUE) |> 
    mutate(month = month.name[month],
      president = prez_gop - prez_dem,
      president = case_when(
          president > 0 ~ "gop",
          president < 0 ~ "dem"),
      year = as.numeric(year)) |> 
    select(-prez_gop, -prez_dem, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Clean the snp.csv data

``` r
snp_df = 
    read_csv("fivethirtyeight_datasets/snp.csv") |> 
    janitor::clean_names() |> 
    separate(date, into = c("month", "day", "year"), convert = TRUE) |> 
    mutate(month = month.name[month],
           year = case_when(
             year <= 15 ~ year + 2000,
             year > 15 ~ year + 1900
           )) |> 
    select(year, month, close, -day)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Clean the unemployment data

``` r
unemployed_df = 
    read_csv("fivethirtyeight_datasets/unemployment.csv") |> 
    janitor::clean_names() |> 
    pivot_longer(
      cols = jan:dec,
      names_to  = "month",
      values_to = "unemployment_percent"
    ) |> 
    mutate(
        month = month.name[match(str_to_title(month), month.abb)]
    )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Merge pols_month_df and snp_df

``` r
pols_snp_df = 
    left_join(pols_month_df, snp_df, by = c("year", "month")) |> 
    select (year, month, president, close, everything())
```

### Merge unemployed_df with pols_month_df

``` r
pols_snp_unemploy_df = 
    left_join(pols_snp_df, unemployed_df, by = c("year", "month")) |> 
    select (year, month, president, close, unemployment_percent, everything())
```

# Question 2

### Clean Mr. Trash Wheel

``` r
mrtrash_df = 
    read_excel("202509 Trash Wheel Collection Data.xlsx", 
                      sheet = "Mr. Trash Wheel",
                      range = "A2:N709",
                      na = c("na", ".", "")) |> 
    janitor::clean_names() |> 
    mutate(
      sports_balls = as.integer(round(sports_balls)),
      data = "mrtrash",
      year = as.numeric(year)) |> 
      select(month, year, date, data, everything(), -dumpster)
```

### Clean Professor Trash Wheel

``` r
prof_trash_df =
    read_excel("202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Professor Trash Wheel",
                    range = "A2:M134",
                    na = c(".", "NA", "")) |> 
    janitor::clean_names() |> 
    mutate(
        data = "prof_trash"
    ) |> 
    select(month, year, date, data, everything(), -dumpster)
```

### Clean Gwynns Falls Wheel Trash Wheel

``` r
gwynns_df = 
    read_excel("202509 Trash Wheel Collection Data.xlsx",
                  sheet = "Gwynns Falls Trash Wheel",
                  range = "A2:L351",
                  na = c(".", "NA", "")) |> 
    janitor::clean_names() |> 
    mutate(
        data = "gwynns"
    ) |> 
    select(month, year, date, data, everything(), -dumpster)
```

### Bind the data sets together

``` r
bind_trash_df = 
    bind_rows(mrtrash_df, prof_trash_df, gwynns_df) |> 
    janitor::clean_names() |> 
    arrange(date)
```

- In the combined data set of Mr. Trash, Professor Trash, and Gwynnda
  called bind_trash_df, there are 1188 observations and 14 variables.
  The key variables include the times of data collection (`month`,
  `year`, `date`), the trash wheel data set identifier (`data`), the
  weight of trash in tons (`weight_tons`), and trash counts
  (`plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
  `plastic_bags`, `wrappers`, and `sports_balls`).

- The total weight of trash collected by Professor Trash Wheel is 282.26
  tons.

- The total number of cigarette butts collected by Gwynns Falls in June
  of 2022 is 18120 butts.

# Question 3

### Load Zip Codes

``` r
zip_codes_df = 
    read_csv("zillow_data/Zip Codes.csv", na = c(".","NA","")) |> 
    janitor::clean_names() |> 
    mutate(county = 
             case_match(county,
                        "New York" ~ "Manhattan", .default = county),
            zip_code = as.character(zip_code)) |> 
    select(county, zip_code, neighborhood, everything(), -state_fips, - county_code, -county_fips, - file_date)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Load Zillow Observed Rent Index (ZORI) in New York City between January 2015 and August 2024

``` r
zori_df = 
      read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", 
               na = c(".", "NA", "")) |> 
      janitor::clean_names() |> 
      rename(
          zip_code = region_name,
          county = county_name) |> 
      pivot_longer(
         cols = x2015_01_31:x2024_08_31,
         names_to = "date",
         values_to = "rental_price",
        names_prefix = "x") |> 
      mutate(county = replace(county, county == "New York County", "Manhattan"),
            county = str_replace(county, " County", ""),
            zip_code = as.character(zip_code),
            date = as.Date(str_replace_all(date, "_", "-"), format = "%Y-%m-%d")) |> 
        select(county, zip_code, date, rental_price, everything(),-state_name) |> 
        arrange(date)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Merge zori_df and zip_codes_df

We want to priortize zori_df with the date and price information. We
will now merge zori_df and zip_codes_df.

``` r
zip_zori_df = 
  left_join(zori_df, zip_codes_df, by =c("zip_code", "county")) |> 
  select(county, zip_code, neighborhood, date, rental_price, everything()) |> 
  arrange(county, zip_code, date)
```

Make a table to compare rental prices in January 2021 to prices in
January 2020

``` r
zip_zori_sep_df <-zip_zori_df |> 
  separate(date, into = c("year", "month", "day"), convert = TRUE) |> 
  filter(year %in% c(2020, 2021), month == 1, day == 31) |> 
  select(zip_code, county, neighborhood, year, month, rental_price) |>
  pivot_wider(
    names_from = year,
    values_from = rental_price) |> 
  mutate(price_diff = `2021` - `2020`) |> 
  arrange(price_diff) |> slice_head(n = 10)
```

- There are 17284 observations and 11 variables. There are key
  variables, such as `county`, `zip_code`, `neighborhood`, `date`, and
  `rental_price`. We are able to see

- In `zip_zori_df`, there are 149 unique zip codes and 42 unique
  neighborhoods.

- 171 ZIP codes appear in the ZIP code dataset but not in the Zillow
  Rental Price dataset.

  - These are the zipcodes below: 10464, 10474, 10475, 10499, 10550,
    10704, 10705, 10803, 11202, 11224, 11239, 11241, 11242, 11243,
    11245, 11247, 11251, 11252, 11256, 10008, 10020, 10041, 10043,
    10045, 10047, 10048, 10055, 10072, 10080, 10081, 10082, 10087,
    10101, 10102, 10103, 10104, 10105, 10106, 10107, 10108, 10109,
    10110, 10111, 10112, 10113, 10114, 10115, 10116, 10117, 10118,
    10119, 10120, 10121, 10122, 10123, 10124, 10125, 10126, 10129,
    10130, 10131, 10132, 10133, 10138, 10149, 10150, 10151, 10152,
    10153, 10154, 10155, 10156, 10157, 10158, 10159, 10160, 10161,
    10163, 10164, 10165, 10166, 10167, 10168, 10169, 10170, 10171,
    10172, 10173, 10174, 10175, 10176, 10177, 10178, 10179, 10185,
    10197, 10199, 10213, 10242, 10249, 10256, 10259, 10260, 10261,
    10265, 10268, 10269, 10270, 10271, 10272, 10273, 10274, 10275,
    10276, 10277, 10278, 10279, 10281, 10285, 10286, 10292, 11001,
    11004, 11005, 11040, 11096, 11351, 11352, 11359, 11362, 11363,
    11371, 11380, 11381, 11386, 11405, 11411, 11412, 11413, 11414,
    11416, 11417, 11419, 11420, 11421, 11422, 11423, 11424, 11425,
    11427, 11428, 11429, 11430, 11431, 11433, 11436, 11439, 11451,
    11499, 11559, 11580, 11690, 11694, 11695, 11697, 10302, 10307,
    10309, 10310, 10311, 10313
  - Some of these zipcodes in `zip_codes_df` aren’t in `zori_df` becuase
    they are in commercial, financial, and government areas, such as
    around the World Trade Center (10048), the NY Stock Exchange
    (10043), and JFK airport (11430). These are nonresidential, so they
    are excluded from Zillow.

``` r
zip_zori_sep_df |>  knitr::kable()
```

| zip_code | county | neighborhood | month | 2020 | 2021 | price_diff |
|:---|:---|:---|---:|---:|---:|---:|
| 10007 | Manhattan | Lower Manhattan | 1 | 6334.211 | 5421.614 | -912.5966 |
| 10069 | Manhattan | NA | 1 | 4623.042 | 3874.918 | -748.1245 |
| 10009 | Manhattan | Lower East Side | 1 | 3406.442 | 2692.187 | -714.2550 |
| 10016 | Manhattan | Gramercy Park and Murray Hill | 1 | 3731.135 | 3019.431 | -711.7045 |
| 10001 | Manhattan | Chelsea and Clinton | 1 | 4108.098 | 3397.648 | -710.4499 |
| 10002 | Manhattan | Lower East Side | 1 | 3645.416 | 2935.113 | -710.3028 |
| 10004 | Manhattan | Lower Manhattan | 1 | 3149.658 | 2443.697 | -705.9608 |
| 10038 | Manhattan | Lower Manhattan | 1 | 3573.201 | 2875.616 | -697.5853 |
| 10012 | Manhattan | Greenwich Village and Soho | 1 | 3628.566 | 2942.344 | -686.2218 |
| 10010 | Manhattan | Gramercy Park and Murray Hill | 1 | 3697.284 | 3012.353 | -684.9304 |

- In general, rental prices in January 2021 to prices in January 2020
  dropped (range: -684.9304, -912.5966). The top 10 largest drop in
  price within the time periods were all in Manhattan county, although
  the neighborhoods spanned across Lower Manhattan, Lower East Side,
  Gramercy Park and Murray Hill, Chelsea and Clinton, and Greenwich
  Village and Soho. The greatest price drop was in Lower Manhattan,
  Manhattan at 10007 (zipcode).
